# -*- coding: utf-8 -*-
"""performance_profiler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TViM9usi-dvXTl2EBJwN9Ziu0MO80Fjc
"""

start_time = time.time()
kmeans_model = kmeans.fit(train_df)
kmeans_time = time.time() - start_time
print(f"K-Means completed in {kmeans_time:.2f}s")

start_time = time.time()
bkmeans_model = bkmeans.fit(train_df)
bkmeans_time = time.time() - start_time
print(f"Bisecting K-Means completed in {bkmeans_time:.2f}s")

start_time = time.time()
gmm_model = gmm.fit(train_df)
gmm_time = time.time() - start_time
print(f"GMM completed in {gmm_time:.2f}s")

start_time = time.time()
rf_model = rf.fit(train_df)
rf_time = time.time() - start_time
print(f"Random Forest completed in {rf_time:.2f}s")

start_time = time.time()
lr_model = lr.fit(train_df)
lr_time = time.time() - start_time
print(f"Logistic Regression completed in {lr_time:.2f}s")

start_time = time.time()
cv_model = crossval.fit(train_sample)
cv_time = time.time() - start_time
print(f"Hyperparameter tuning completed in {cv_time:.2f}s")

stability_results = []
for seed in seeds:
    start_time = time.time()
    kmeans_stability = KMeans(featuresCol="features", predictionCol="cluster", k=best_k['k'], seed=seed, maxIter=20)
    model = kmeans_stability.fit(train_df)
    stability_time = time.time() - start_time
    stability_results.append({'seed': seed, 'silhouette': silhouette, 'wssse': model.summary.trainingCost, 'time': stability_time})
    print(f"Seed {seed}: Stability Time={stability_time:.2f}s")

scalability_results = []
for size in sample_sizes:
    start_time = time.time()
    kmeans_scale = KMeans(featuresCol="features", predictionCol="cluster", k=5, seed=42, maxIter=10)
    model = kmeans_scale.fit(sample)
    training_time = time.time() - start_time
    scalability_results.append({'sample_size': size, 'training_time_sec': training_time})
    print(f"Training on {size*100:.0f}%: Time={training_time:.2f}s")

stability_df = pd.DataFrame(stability_results)
stability_df.to_csv('stability_analysis.csv', index=False)

scalability_df = pd.DataFrame(scalability_results)
scalability_df.to_csv('scalability_analysis.csv', index=False)