# -*- coding: utf-8 -*-
"""run_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U6dPJtO2QmqAVTZr7QYw2fuU2BGRqI1H
"""

from datasets import load_dataset
from pyspark.sql import SparkSession

# Initialize Spark Session
spark = SparkSession.builder \
    .appName("MiniPile_Analysis") \
    .config("spark.driver.memory", "4g") \
    .master("local[*]") \
    .getOrCreate()

# Load Dataset
dataset = load_dataset("JeanKaddour/minipile")

# Convert to Pandas DataFrame and then to Spark DataFrame
pandas_df = dataset["train"].select(range(10000)).to_pandas()
spark_df = spark.createDataFrame(pandas_df)

from pyspark.sql.functions import length, size, split, regexp_replace, col

# Add various features like word count, character count, punctuation count, etc.
spark_df = spark_df.withColumn("char_count", length(col("text")))
spark_df = spark_df.withColumn("word_count", size(split(col("text"), " ")))
spark_df = spark_df.withColumn(
    "sentence_count",
    length(regexp_replace(col("text"), "[^.!?]", ""))
)
# Additional feature engineering code follows...

from pyspark.ml.clustering import KMeans, BisectingKMeans, GaussianMixture
from pyspark.ml.classification import RandomForestClassifier, LogisticRegression

# K-Means Clustering
kmeans = KMeans(featuresCol="features", predictionCol="cluster", k=3, seed=42)
kmeans_model = kmeans.fit(train_df)

# Bisecting K-Means
bkmeans = BisectingKMeans(featuresCol="features", predictionCol="bkmeans_cluster", k=3, seed=42)
bkmeans_model = bkmeans.fit(train_df)

# GMM
gmm = GaussianMixture(featuresCol="features", predictionCol="gmm_cluster", k=3, seed=42)
gmm_model = gmm.fit(train_df)

# Random Forest
rf = RandomForestClassifier(featuresCol="features", labelCol="length_category_idx", predictionCol="rf_prediction", numTrees=50, maxDepth=10, seed=42)
rf_model = rf.fit(train_df)

# Logistic Regression
lr = LogisticRegression(featuresCol="features", labelCol="length_category_idx", predictionCol="lr_prediction", maxIter=100, regParam=0.01, elasticNetParam=0.0, family="multinomial")
lr_model = lr.fit(train_df)

from pyspark.ml.evaluation import MulticlassClassificationEvaluator

# Evaluate Random Forest
evaluator_acc = MulticlassClassificationEvaluator(labelCol="length_category_idx", predictionCol="rf_prediction", metricName="accuracy")
train_accuracy = evaluator_acc.evaluate(train_pred_rf)
val_accuracy = evaluator_acc.evaluate(val_pred_rf)
test_accuracy = evaluator_acc.evaluate(test_pred_rf)

# Evaluate Logistic Regression
evaluator_lr_acc = MulticlassClassificationEvaluator(labelCol="length_category_idx", predictionCol="lr_prediction", metricName="accuracy")
train_accuracy_lr = evaluator_lr_acc.evaluate(train_pred_lr)
val_accuracy_lr = evaluator_lr_acc.evaluate(val_pred_lr)
test_accuracy_lr = evaluator_lr_acc.evaluate(test_pred_lr)

# Save models for future use
rf_model.write().overwrite().save("models/rf_model")
lr_model.write().overwrite().save("models/lr_model")

# Export data for Tableau
sample_export = test_df.select('doc_id', 'word_count', 'char_count', 'sentence_count', 'lexical_diversity', 'complexity_score', 'length_category', 'rf_prediction').toPandas()
sample_export.to_csv('tableau_sample_data.csv', index=False)