# -*- coding: utf-8 -*-
"""test_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HIrOfncGxKsSQRdSaSqReOkXmHxrha0Y
"""

def test_data_ingestion():
    dataset = load_dataset("JeanKaddour/minipile")
    assert dataset is not None, "Dataset loading failed"

    pandas_df = dataset["train"].select(range(10000)).to_pandas()
    assert not pandas_df.empty, "Pandas DataFrame is empty"

    spark_df = spark.createDataFrame(pandas_df)
    assert spark_df.count() > 0, "Spark DataFrame is empty"

def test_feature_engineering():
    spark_df = spark.createDataFrame(pandas_df)

    # Test if the feature "char_count" is created
    assert spark_df.columns.count("char_count") > 0, "'char_count' feature missing"

    # Test if "word_count" is calculated correctly
    word_count_sample = spark_df.select("word_count").head(1)[0]["word_count"]
    assert isinstance(word_count_sample, int), "'word_count' is not an integer"

def test_kmeans_training():
    kmeans = KMeans(featuresCol="features", predictionCol="cluster", k=3, seed=42)
    kmeans_model = kmeans.fit(train_df)
    assert kmeans_model is not None, "K-Means training failed"

def test_rf_training():
    rf = RandomForestClassifier(featuresCol="features", labelCol="length_category_idx", predictionCol="rf_prediction")
    rf_model = rf.fit(train_df)
    assert rf_model is not None, "Random Forest training failed"

def test_rf_evaluation():
    evaluator = MulticlassClassificationEvaluator(labelCol="length_category_idx", predictionCol="rf_prediction", metricName="accuracy")
    accuracy = evaluator.evaluate(test_pred_rf)
    assert accuracy >= 0, "Accuracy evaluation failed"

    evaluator_f1 = MulticlassClassificationEvaluator(labelCol="length_category_idx", predictionCol="rf_prediction", metricName="f1")
    f1 = evaluator_f1.evaluate(test_pred_rf)
    assert f1 >= 0, "F1 Score evaluation failed"

def test_data_quality():
    null_counts = spark_df.select([count(when(col(c).isNull(), c)).alias(c) for c in spark_df.columns if c != 'text']).collect()[0].asDict()
    for col_name, null_count in null_counts.items():
        assert null_count == 0, f"Column {col_name} contains {null_count} null values"

    # Test that no documents with less than 5 words are present
    filtered_df = spark_df.filter(col("word_count") > 5)
    assert filtered_df.count() == spark_df.count(), "Some rows have been filtered out with less than 5 words"

def test_saving_results():
    rf_model.write().overwrite().save("models/rf_model")
    assert os.path.exists("models/rf_model"), "Random Forest model not saved"

    sample_export = test_df.select('doc_id', 'word_count', 'char_count', 'complexity_score').toPandas()
    sample_export.to_csv('tableau_sample_data.csv', index=False)
    assert os.path.exists('tableau_sample_data.csv'), "Sample data not saved for Tableau"